### ISSUE TITLE
optimize_stencil.py completely broken

### ISSUE THREAD

**Issue by stetie** [Ablinne/optimize-stencil#1]
I installed the package as described in the Readme. When I try to run optimize_stencil.py, even without any argument, I get the following stack trace:
https://gist.github.com/stetie/5db3d72dc68b620bbb6c08e674f657a5

Used software version:
Python 3.6.5
Numpy 1.14.3

**Comment by Ablinne** [comment]
This was due to a change from numpy 1.13 to numpy 1.14 about how `numpy.recarray` handles assignments. Although the change was announced already in 1.13's documentation, the code I had written for 1.14 back then was never tested. Well, let's just say it was almost correct...

**Comment by Ablinne** [comment]
fixed by 8edaa4f73a0ea9af8a16f77fa37d1e7082152f23
